### ISSUE TITLE
PLCC script generation

### ISSUE THREAD

**Issue by Misca1234** [KiCad/Housings_LCC.pretty#5]
Accorind to push 
https://github.com/KiCad/Housings_LCC.pretty/pull/2

the foot print is script generated but I can not find and 'PLCC' in kicad-footprint-generator/scripts

Are this script never published or is it a private one ?

**Comment by SchrodingersGat** [comment]
https://github.com/SchrodingersGat/kicad-footprint-generator/tree/master/scripts/PLCC

**Comment by Misca1234** [comment]
huh , would it not be a good idea to put 
https://github.com/SchrodingersGat/kicad-footprint-generator
and 
https://github.com/pointhi/kicad-footprint-generator

together to one ?

**Comment by Misca1234** [comment]
Hmm, yours is a fork of his, I need to refork yours
but i have to wait until my pushes to his are done

**Comment by SchrodingersGat** [comment]
@Misca1234 

In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)
