### ISSUE TITLE
PLCC84-THT socket is broken

### ISSUE THREAD

**Issue by nils-eilers** [KiCad/Housings_LCC.pretty#6]
Pin 76 and pin 76 are located at the same place

  (pad 73 thru_hole circle (at 12.7 2.54) (size 1.75 1.75) (drill 0.95) (layers *.Cu *.Mask))
  (pad 76 thru_hole circle (at 12.7 2.54) (size 1.75 1.75) (drill 0.95) (layers *.Cu *.Mask))

**Comment by SchrodingersGat** [comment]
Are you able to supply a fix for this issue?

**Comment by nils-eilers** [comment]
There seem to be some more problems with this library. Unfortunately I'm going to a vacation for a couple of days but yes, I could supply patches afterwards.

**Comment by SchrodingersGat** [comment]
@nils-eilers 



In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)
